version: '3'

services:

  db:
    image: postgres:12.10
    restart: always
    container_name: ticketing_db
    volumes:
      - ./volumes/ps_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}

  web:
    restart: always
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    container_name: ticketing_web
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    env_file: .env
    command: gunicorn --bind 0.0.0.0:8000 ticketing.wsgi
    entrypoint: /entrypoint.sh
    depends_on:
      - db